vagabond_app/config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "welcome#index"

  get '/login', to: "sessions#new"
  post '/sessions', to: "sessions#create"
  delete '/sessions', to: 'sessions#destroy', as: 'destroy_session'
# ..
end

vagabond_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vagabond_app/app/models/city.rb
class City < ApplicationRecord
	has_many :posts
end

vagabond_app/app/models/post.rb
class Post < ApplicationRecord
	validates :title, length: {maximum: 200}, presence: true
	validates :content, presence: true
	belongs_to :user
	belongs_to :city
end

vagabond_app/app/models/session.rb
class Session < ActiveRecord::Base
end

vagabond_app/app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	has_many :posts
	has_secure_password

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
end

vagabond_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

vagabond_app/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
#
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @posts = Post.where(:city_id => params[:id]).order("created_at DESC")
    @city = City.find_by_id(params[:id])
    render :show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:city_name, :description, :img_url)
    end
end

vagabond_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
  end

  # GET /posts/new
  def new
    @post = Post.new

  end

  # GET /posts/1/edit
  def edit
    @post = Post.find_by_id(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params

      params.require(:post).permit(:title, :content, :post_date, :city_id, :user_id)
    end
end

vagabond_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new 
		@user = User.new
		render :new
	end

	def create 
		@user = User.confirm(user_params)
		if @user 
			login(@user)
			redirect_to "/users/#{@user.id}"
		else 

			redirect_to '/login'
		end
	end

	def destroy
		logout
		redirect_to '/login'
	end




	private 
	def user_params
		params.require(:user).permit(:email, :password)
	end
				


end

vagabond_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user=User.find_by_id(params[:id])
    # @posts= Post.find(:all, :conditions => {:user_id => params[:id]})
  
    @posts=Post.where(:user_id => params[:id])
    render :show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.join_date = Date.today

    # respond_to do |format|
      if @user.save
        login(@user)
        redirect_to "/users/#{@user.id}"
        # format.html { redirect_to @user, notice: 'User was successfully created.' }
        # format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :fname, :lname, :current_city, :join_date, :password, :password_confirmation)
    end
end

vagabond_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index 
		render :index		
	end

end

vagabond_app/app/helpers/application_helper.rb
module ApplicationHelper
end

vagabond_app/app/helpers/cities_helper.rb
module CitiesHelper
end

vagabond_app/app/helpers/posts_helper.rb
module PostsHelper
end

vagabond_app/app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to "/login"
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

vagabond_app/app/helpers/users_helper.rb
module UsersHelper
end

vagabond_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

vagabond_app/app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city_name %>
    <%= f.text_field :city_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vagabond_app/app/views/cities/edit.html.erb
<div id="editingcity">
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>
</div>

vagabond_app/app/views/cities/index.html.erb
<div id="indexcity">

<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>City name</th>
      <th>Description</th>
      <th>Img url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.city_name %></td>
        <td><%= city.description %></td>
        <td><%= city.img_url %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>
</div>

vagabond_app/app/views/cities/new.html.erb
<div id="newcity">
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>
</div>

vagabond_app/app/views/cities/show.html.erb
<style type="text/css">
	#welcomebackground{
		background-image: url(<%= @city.img_url %> );
	}
</style>

<div id="cityInfo">
<h1>Posts</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>City name:</strong>
  <%= @city.city_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @city.description %>
</p>


  <ul>
    <% @posts.each do |posts| %>
    <li><%= link_to "#{posts.title}", post_path(posts.id), method: :get %></a></li>
    <%end%>
  </ul>
<div id="addpostbutton">
<%= button_to "Add new Post", new_post_path, method: :get, params: {city_id: @city.id, user_id: session[:user_id]} %>
</div><br />
<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

</div>

vagabond_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagabondApp</title>
        <%= csrf_meta_tags %>

   <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="welcomebackground"></div> 
       <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Vagabond</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if session[:user_id] == nil %>
          <li class="active"><a href="/login">Log In<span class="sr-only">(current)</span></a></li>
        <%end%>
        <% if session[:user_id] == nil %>
          <li><a href="/users/new" >Sign UP</a></li>
        <%end%>
        <% if session[:user_id] != nil %>
          <li><%= link_to "Logout", destroy_session_path, method: :delete %></li>
        <%end%>
      </ul>
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
       
       
        <%= yield %>
    
    <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
  </body>
</html>

vagabond_app/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :post_date %>
    <%= f.date_select :post_date %>
  </div>

   <div class="field">
    <%= f.label :city_id %>
    <%= f.text_field :city_id, :value => params[:city_id], :readonly => true %>
  </div>

   <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, :value => params[:user_id], :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vagabond_app/app/views/posts/_form_edit.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :post_date %>
    <%= f.date_select :post_date %>
  </div>

   <div class="field">
    <%= f.hidden_field :city_id, :value => @post[:city_id], :readonly => true %>
  </div>

   <div class="field">
    <%= f.hidden_field :user_id, :value => @post[:user_id], :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vagabond_app/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form_edit'%>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

vagabond_app/app/views/posts/index.html.erb
<div id="post">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Post date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.post_date %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</div>

vagabond_app/app/views/posts/new.html.erb
<div id="newpost">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

vagabond_app/app/views/posts/show.html.erb
<div class="post">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <%= @post.title %>
	</p>

	<p>
	  <strong>Content:</strong>
	  <%= @post.content %>
	</p>

	<p>
	  <strong>Post date:</strong>
	  <%= @post.post_date %>
	</p>

	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %> |
	<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure you want to delete ' + @post.title + "?" } %>
</div>

vagabond_app/app/views/users/_form.html.erb
  <%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :fname %>
    <%= f.text_field :fname %>
  </div>

  <div class="field">
    <%= f.label :lname %>
    <%= f.text_field :lname %>
  </div>

  <div class="field">
    <%= f.label :current_city %>
    <%= f.text_field :current_city %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%=f.label :password_confirmation %>
    <%=f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vagabond_app/app/views/users/edit.html.erb
<div id="newuser">
	<h1>Editing User</h1>
	<%= render 'form', user: @user %>
	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
</div>

vagabond_app/app/views/users/index.html.erb
<div id="showuser">
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table id="usertable">
  <thead>
    <tr>
      <th>Email</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Current city</th>
      <th>Join date</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.current_city %></td>
        <td><%= user.join_date %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

vagabond_app/app/views/users/new.html.erb
<div id="newuser">
  <h1>New User</h1>
	<%= render 'form', user: @user %>
	<%= link_to 'Back', users_path %>
</div>

vagabond_app/app/views/users/show.html.erb
<div class="user_information">

  <p id="notice"><%= notice %></p>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <p>
    <strong>First Name:</strong>
    <%= @user.fname %>
  </p>
  <p>
    <strong>Last Name:</strong>
    <%= @user.lname %>
  </p>
  <p>
    <strong>Current City:</strong>
    <%= @user.current_city %>
  </p>
  <p>
    <strong>Join date:</strong>
    <%= @user.join_date %>
  </p>

  <h1>Posts</h1>
    
  <ul>
    <% @posts.each do |posts| %>
    <li><%= link_to "#{posts.title}", post_path(posts.id), method: :get %></a></li>
    <%end%>
  </ul>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>

vagabond_app/app/views/welcome/index.html.erb
<h1 id="welcome" >VAGABOND ADVENTURES!</h1>
<h4>“The biggest adventure you can ever take is to live the life of your dreams.” </h4>